[workspace]
members = [
  "lib/graphics/",
  "lib/mandelbrot/",
  "lib/sceneplotlib/",
  "lib/siunits/",
  "programs/imgview",
  "programs/mandlebrotviewer",
  "programs/sceneplot",
  "programs/phys",
]
