[package]
name = "sceneplot"
version = "0.1.0"
authors = ["Quinten Palmer <quintenpalmer@gmail.com>"]

[dependencies]
graphics = {path = "../../lib/graphics"}
sceneplotlib = {path = "../../lib/sceneplotlib"}
