[package]
name = "mandelbrotviewer"
version = "0.1.0"
authors = ["Quinten Palmer <quintenpalmer@gmail.com>"]

[dependencies]
graphics = {path = "../../lib/graphics"}
mandelbrot = {path = "../../lib/mandelbrot"}
