[package]
name = "plottin"
version = "0.1.0"
authors = ["Quinten Palmer <quintenpalmer@gmail.com>"]

[[bin]]
name = "plotting"
path = "src/main.rs"
test = false
bench = false

[dependencies]
graphics = {path = "../../lib/graphics"}
plotlib = {path = "../../lib/plotlib"}
